### ISSUE TITLE
Virus reports

### ISSUE THREAD

**Issue by Retne** [BlaXpirit/sixcells#6]
Hi.

Kaspersky and (I think) Windows Defender thinks there is a virus issue with this (e.g.):

![image](https://user-images.githubusercontent.com/1769707/94821226-4556f980-03f9-11eb-8e3f-d1d4810683da.png)

I don't know Python well enough to look at this in any detail or see what's triggering this. Are you able to modify this?

Thanks!
R

**Comment by oprypin** [comment]
There is no Python involved in editor.exe

The entire source code is
https://github.com/oprypin/sixcells/blob/master/.windows/make_runners.cmd +
https://github.com/oprypin/sixcells/blob/master/.windows/runner.c

**Comment by Retne** [comment]
Thanks for trhe quick reply.

Sorry, I made the comment about python as my assumption is the source code appears to be python (I know... it's a big leap from me ;) ), which I assume is compiled into an exe - the comment about python was me simply saying I'm not able to look at the .py files and see what's triggering this false-positive.

I see also that there are some files adjacent to the exe, but I have no idea how the AV software is working to know if that's an influence here at all (my guess is not, especially as they're not removed, but that's only an assumption, and it might they they'd be removed it I grabbed Python on my machine to try to run (bits of / all of) them directly).
![image](https://user-images.githubusercontent.com/1769707/94830989-11cd9c80-0404-11eb-8f96-08ed7c84626e.png)

My concern (that's perhaps too strong a word!) is that folks will download then think there's a problem with it. I don't know if it could be submitted to Kaspersky / Windows Defender for manual checking?

I'm not suggesting there is a problem with the code itself, but having this false result could be a cause of issues in running the program regardless.

Good editor btw! Appreciate it, and just trying to ensure others can do the same!

**Comment by oprypin** [comment]
Well no, I wouldn't expect it to look at the Python files at all. (Would be nice if someone confirmed that editor.exe completely by itself triggers the silly AV)

Then I think one could even re-build an (almost) identical editor.exe from the source (linked above) using Visual Studio 2015 community ed., to make it obvious that it's not a virus.

In any case, these files are completely optional. `editor.exe`'s entire task is to run `pythonw.exe editor.py`, but you can do that yourself. One way to do it is by dragging "editor.py" *onto* "pythonw.exe".

And yes, I heard Kaspersky has a process to submit a file for review. Guess I'll do that later, unless you want.
And the reason that I heard about this is that it had false positives with both SFML and ImGui projects recently...

**Comment by oprypin** [comment]
Actually I don't know what detection you're talking about. VirusTotal doesn't say that Kaspersky detects it.
https://www.virustotal.com/gui/file/fa02bf6d5a3f62f43c7364d252a4138810af6652d325bb7ac9dc345cb317d103/details
The file is 4 yrs old and VirusTotal knows that too, and if nobody said anything up to now, I don't know...

**Comment by Retne** [comment]
Lost track of this (life got in the way), but yeah, that was odd. TY for looking into it!
